{"author":{"id":"a96f7d14a5a4503f5bd1a13a339569bf2e99c204892144fd7ed5a49b9e36a360"},"ops":[{"type":1,"author":{"id":"a96f7d14a5a4503f5bd1a13a339569bf2e99c204892144fd7ed5a49b9e36a360"},"timestamp":1577161317,"nonce":"Y88ediJvFmAXN27CTVoduSdqDUs=","title":"Support cousins marrying (was: trying to make ged2dot)","message":"has anybody tried this with an Ancestry.com ged download?\nI get an immediate exception about lack of HEAD\n\ni@raspberrypi:~/git/ged2dot $ ./ged2dot.py ../../Hughes\\ Family\\ Tree.ged\nConfiguration invalid? File contains no section headers.\nfile: '../../Hughes Family Tree.ged', line: 1\n'0 HEAD\\n'\nTraceback (most recent call last):\n  File \"./ged2dot.py\", line 953, in main\n    config = Config(sys.argv[1:])\n  File \"./ged2dot.py\", line 849, in __init__\n    self.parse()\n  File \"./ged2dot.py\", line 867, in parse\n    self.parser.read(path)\n  File \"/usr/lib/python3.5/configparser.py\", line 696, in read\n    self._read(fp, filename)\n  File \"/usr/lib/python3.5/configparser.py\", line 1077, in _read\n    raise MissingSectionHeaderError(fpname, lineno, line)\nconfigparser.MissingSectionHeaderError: File contains no section headers.\nfile: '../../Hughes Family Tree.ged', line: 1\n'0 HEAD\\n'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"./ged2dot.py\", line 971, in \u003cmodule\u003e\n    main()\n  File \"./ged2dot.py\", line 957, in main\n    config.usage()\nUnboundLocalError: local variable 'config' referenced before assignment","files":null}]}