{"version":2,"ops":[{"type":1,"author":{"id":"2f0fa937152287176e75fdb4d24b570fbf0d9ba3"},"timestamp":1577161317,"metadata":{"github-id":"MDU6SXNzdWU1NDE5ODQwNTA=","github-url":"https://github.com/vmiklos/ged2dot/issues/13","origin":"github"},"title":"Support cousins marrying (was: trying to make ged2dot)","message":"has anybody tried this with an Ancestry.com ged download?\nI get an immediate exception about lack of HEAD\n\ni@raspberrypi:~/git/ged2dot $ ./ged2dot.py ../../Hughes\\ Family\\ Tree.ged\nConfiguration invalid? File contains no section headers.\nfile: '../../Hughes Family Tree.ged', line: 1\n'0 HEAD\\n'\nTraceback (most recent call last):\n  File \"./ged2dot.py\", line 953, in main\n    config = Config(sys.argv[1:])\n  File \"./ged2dot.py\", line 849, in __init__\n    self.parse()\n  File \"./ged2dot.py\", line 867, in parse\n    self.parser.read(path)\n  File \"/usr/lib/python3.5/configparser.py\", line 696, in read\n    self._read(fp, filename)\n  File \"/usr/lib/python3.5/configparser.py\", line 1077, in _read\n    raise MissingSectionHeaderError(fpname, lineno, line)\nconfigparser.MissingSectionHeaderError: File contains no section headers.\nfile: '../../Hughes Family Tree.ged', line: 1\n'0 HEAD\\n'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"./ged2dot.py\", line 971, in \u003cmodule\u003e\n    main()\n  File \"./ged2dot.py\", line 957, in main\n    config.usage()\nUnboundLocalError: local variable 'config' referenced before assignment","files":null}]}