{"author":{"id":"55f32365b2b3e9b177769e379b4d68f0b5b828247242a6a32097bf0f6d5ae99f"},"ops":[{"type":3,"author":{"id":"55f32365b2b3e9b177769e379b4d68f0b5b828247242a6a32097bf0f6d5ae99f"},"timestamp":1577198499,"nonce":"i3jzx/fP1d2QmCEMKUH+uy9XvwY=","message":"I played around with it, trying to get it to NOT move people too far away\nfrom when they should be, but after 3 generations, it's totally impossible\nto control the dot algorithm that tried to shorten lines.\n\nIt's also confused by cousins marrying, which is quite common up to 100\nyears ago (1920s in my case) so that limits how far back a tree is\npossible.  (Technically, we want to draw a graph with loops, not a tree).\n\nOn Mon, Dec 23, 2019 at 11:21 PM Doug Hughes \u003cnotifications@github.com\u003e\nwrote:\n\n\u003e has anybody tried this with an Ancestry.com ged download?\n\u003e I get an immediate exception about lack of HEAD\n\u003e\n\u003e i@raspberrypi:~/git/ged2dot $ ./ged2dot.py ../../Hughes\\ Family\\ Tree.ged\n\u003e Configuration invalid? File contains no section headers.\n\u003e file: '../../Hughes Family Tree.ged', line: 1\n\u003e '0 HEAD\\n'\n\u003e Traceback (most recent call last):\n\u003e File \"./ged2dot.py\", line 953, in main\n\u003e config = Config(sys.argv[1:])\n\u003e File \"./ged2dot.py\", line 849, in *init*\n\u003e self.parse()\n\u003e File \"./ged2dot.py\", line 867, in parse\n\u003e self.parser.read(path)\n\u003e File \"/usr/lib/python3.5/configparser.py\", line 696, in read\n\u003e self._read(fp, filename)\n\u003e File \"/usr/lib/python3.5/configparser.py\", line 1077, in _read\n\u003e raise MissingSectionHeaderError(fpname, lineno, line)\n\u003e configparser.MissingSectionHeaderError: File contains no section headers.\n\u003e file: '../../Hughes Family Tree.ged', line: 1\n\u003e '0 HEAD\\n'\n\u003e\n\u003e During handling of the above exception, another exception occurred:\n\u003e\n\u003e Traceback (most recent call last):\n\u003e File \"./ged2dot.py\", line 971, in\n\u003e main()\n\u003e File \"./ged2dot.py\", line 957, in main\n\u003e config.usage()\n\u003e UnboundLocalError: local variable 'config' referenced before assignment\n\u003e\n\u003e â€”\n\u003e You are receiving this because you are subscribed to this thread.\n\u003e Reply to this email directly, view it on GitHub\n\u003e \u003chttps://github.com/vmiklos/ged2dot/issues/13?email_source=notifications\u0026email_token=AEVUPLJFKTYR2HYZX2DPZSDQ2GE6NA5CNFSM4J62O4U2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4ICOAUZA\u003e,\n\u003e or unsubscribe\n\u003e \u003chttps://github.com/notifications/unsubscribe-auth/AEVUPLJMY3XCBI56PJDJ4HLQ2GE6NANCNFSM4J62O4UQ\u003e\n\u003e .\n\u003e\n-- \nGregg Tracton: tired, retired \u0026 inappropriately unattired (PJ's)","files":null}]}